### ISSUE TITLE
Not able to install with devtools

### ISSUE THREAD

**Issue by schrauf** [syabe/BreedingSchemeLanguage#2]
Hello,
very nice simulation scheme, particulary like the interface and would be very interested to try it.
Unfortunately, installing with devtools is not working for me. Do you have any idea why that could be? It doesn't seem to be compiling the c++ code, here is the output.

```
> devtools::install_github("syabe/BreedingSchemeLanguage")
Downloading GitHub repo syabe/BreedingSchemeLanguage@master
from URL https://api.github.com/repos/syabe/BreedingSchemeLanguage/zipball/master
Installing BreedingSchemeLanguage
'/usr/lib/R/bin/R' --no-site-file --no-environ --no-save --no-restore --quiet CMD INSTALL  \
  '/tmp/RtmpiHqoY6/devtools3a4be2013cf/syabe-BreedingSchemeLanguage-98a07e3'  \
  --library='[my_libs_dir]' --install-tests 

* installing *source* package ‘BreedingSchemeLanguage’ ...
** libs
make: Nothing to be done for 'all'.
installing to [my_libs_dir]/BreedingSchemeLanguage/libs
** R
** preparing package for lazy loading
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded
Error: package or namespace load failed for ‘BreedingSchemeLanguage’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '[my_libs_dir]/BreedingSchemeLanguage/libs/BreedingSchemeLanguage.so':
  [my_libs_dir]/BreedingSchemeLanguage/libs/BreedingSchemeLanguage.so: invalid ELF header
Error: loading failed
Execution halted
ERROR: loading failed
* removing ‘[my_libs_dir]/BreedingSchemeLanguage’
Installation failed: Command failed (1)
```

In any case, thank you for your time, Matías

**Comment by syabe** [comment]
This error message was the first case for me. So I am not sure if I know any suitable  @solutions.
I recommend you to try solutions below:

1. change the option to install BSL
In DOS-command prompt, the option "-no-multiarch" is sometimes valid.
   library(devtools)
   install_github(PACKAGE, args="--no-multiarch")
might be worth a try. This solution worked well for Windows machine so far.

2. use the older version of R
One user reported that the older version of R (e.g., R3.2.4) was better to use BSL. He was a Mac user.

3. remove pre-installed BSL from your PC and install BSL again (especially for Windows user)
On Windows machine, sometimes they cannot install and overwrite the package when the package has been installed partially. (If the BSL has been installed partially, Windows machine cannot install the new BSL.)
So, I think that it is better to remove the folder "BreedingSchemeLanguage" from the directory you installed BSL (e.g., "C:/Users/msi33/Documents/R/win-library/3.3") before you re-install the package.

Thank you for your caution and helpful kindness.
Shiori

**Comment by schrauf** [comment]
Thanks for the quick response!
I'm using Linux, so I could not try your suggestions.

Anyway, the issue seemed to be that you are keeping the .o .so and .dll files in the /src directory. This is keeping R from compiling them itself, with ensuing problems. At least for my case, cloning your repo with git, deleting the the problematic files and building with R solved this particular problem.

In case it helps anybody, here is the code:
```
git clone https://github.com/syabe/BreedingSchemeLanguage.git
rm BreedingSchemeLanguage/src/*.o
rm BreedingSchemeLanguage/src/BreedingSchemeLanguage.so
rm BreedingSchemeLanguage/src/BreedingSchemeLanguage.dll
R CMD build BreedingSchemeLanguage
R CMD INSTALL BreedingSchemeLanguage_1.0.tar.gz
```

Looking forward to try your simulator.
Cheers!
